### ISSUE TITLE
Deprecated functions in Python 3.8 used in FMPy

### ISSUE THREAD

**Issue by debuti** [CATIA-Systems/FMPy#105]
Seems like the pyqtgraph version fmpy is using is not updated to work with python 3.8, as it removed the clock() function from the time module

```
Traceback (most recent call last):
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fmpy\gui\__main__.py", line 7, in <module>
    from fmpy.gui.MainWindow import MainWindow
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fmpy\gui\MainWindow.py", line 16, in <module>
    from fmpy.gui.generated.MainWindow import Ui_MainWindow
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fmpy\gui\generated\MainWindow.py", line 907, in <module>
    from pyqtgraph import GraphicsLayoutWidget
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import *
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "C:\Users\debuti\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by t-sommer** [comment]
This problem has been fixed (see https://github.com/conda-forge/pyqtgraph-feedstock/issues/10).
