### ISSUE TITLE
fmpy estimates resources in wrong location for Linux FMUs

### ISSUE THREAD

**Issue by DaJansenGit** [CATIA-Systems/FMPy#236]
It seems I come across an error with Linux FMUs with external resources. 
If I export a FMU under Dymola 2020 in Linux which has an external .mat file as table, this .mat file is correctly integrated into FMU in the resources folder.
Importing this FMU back to dymola works fine. This test was performced on another machine, to make sure, that no pointers to local pathes are the reason for the working FMU.
When simulating the same FMU with fmpy I get the following error.
```
~/fmitest/fmu$ fmpy simulate RelativePathTest.fmu
[ERROR] Error: The following error was detected at time: 0
[ERROR] Not possible to open file "tmp/tmp9550oksr/resources/TemperaturesConv.mat": No such file or directory

[ERROR] The stack of functions is:
[ERROR] Modelica.Blocks.Types.ExternalCombiTimeTable
[ERROR] Modelica.Blocks.Types.ExternalCombiTimeTable((if combiTimeTable.tableOnFile then combiTimeTable.tableName else "NoName"), (if combiTimeTable.tableOnFile and combiTimeTable.fileName <> "NoName" and  not Modelica.Utilities.Strings.isEmpty(combiTimeTable.fileName) then combiTimeTable.fileName else "NoName"), combiTimeTable.table, combiTimeTable.startTime/combiTimeTable.timeScale, combiTimeTable.co...
[ERROR] fmiInitialize: dsblock_ failed, QiErr = 1
[ERROR] Unless otherwise indicated by error messages, possible errors are (non-exhaustive):
The model references external data that is not present on the target machine, at least not with the same location.

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/fmpy", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/fmpy/command_line.py", line 137, in main
    result = simulate_fmu(args.fmu_filename,
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/fmpy/simulation.py", line 696, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/fmpy/simulation.py", line 1099, in simulateCS
    fmu.enterInitializationMode()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/fmpy/fmi2.py", line 283, in enterInitializationMode
    return self.fmi2EnterInitializationMode(self.component)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/fmpy/fmi2.py", line 215, in w
    raise Exception("%s failed with status %d." % (fname, res))
Exception: fmi2EnterInitializationMode failed with status 3.

```
So fmpy seems to estimate the resources in some local path which is not existing. 
I attached a test FMU which shows the problem.
[testfmu.zip](https://github.com/CATIA-Systems/FMPy/files/6042348/testfmu.zip)

If there is anything unclear, don't hesitate to ask 

**Conditions:**
* fmpy 0.2.27 
* Python 3.8 
* Dymola Version 2020 (64-bit), 2019-04-10

**Edit:**
Under windows everything works fine when using Dymola Version 2021 (64-bit), 2020-04-17

**Comment by t-sommer** [comment]
This is a bug in the FMU. The path `tmp/tmp9550oksr/resources/TemperaturesConv.mat` is missing a leading `/` and thus is relative to the current working directory. A workaround is to change the working directory of your process to `/` (root):

```
user@host:/somewhere/$ cd /
user@host:/$ fmpy simulate /path/to/RelativePathTest.fmu --fmi-logging
[FMI] fmi2Instantiate(instanceName="RelativePathTest", fmuType=1, guid="{e920613d-1315-4336-9bfb-f3831ad6851b}", resourceLocation="file:///tmp/tmpzpci792q/resources", callbacks=<fmpy.fmi2.fmi2CallbackFunctions object at 0x7f94b580af28>, visible=0, loggingOn=0) -> 0x1be58a0
[FMI] fmi2SetupExperiment(component=0x1be58a0, toleranceDefined=1, tolerance=0.0001, startTime=0.0, stopTimeDefined=0, stopTime=0.0) -> OK
[FMI] fmi2EnterInitializationMode(component=0x1be58a0) -> OK
[FMI] fmi2ExitInitializationMode(component=0x1be58a0) -> OK
[FMI] fmi2GetReal(component=0x1be58a0, vr=[335544320], nvr=1, value=[295.15]) -> OK
[FMI] fmi2DoStep(component=0x1be58a0, currentCommunicationPoint=0.0, communicationStepSize=0.002, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1be58a0, vr=[335544320], nvr=1, value=[295.1499767044067]) -> OK
...
```

**Comment by Maghnie** [comment]
I object. Interesting conjecture that it is a bug in the FMU, but how do we know it's not fmpy that set up this false path? Isn't it fmpy's task to unpack the FMU? (Hope this is not overruled)

**Comment by Maghnie** [comment]
Changing the working directory of my process was a bit more complicated than I thought, but a quick workaround that worked was adding a forward slash to the `resourceLocatio` path in fmpy:

![image](https://user-images.githubusercontent.com/68941589/109417949-12c02580-79c6-11eb-9b45-9e56f11012e2.png)
