### ISSUE TITLE
Could not load shared library with release 0.2.27

### ISSUE THREAD

**Issue by PhillipEDRDK** [CATIA-Systems/FMPy#237]
Hi, 

I updated from fmpy==0.2.26 to 0.2.27. I am running a FMU generated in TwinBuilder from a .twin file. I am running Python 3.8.3 on Windows 10. It is a CoSimulation FMU 2.0.

When running the FMU I get this error message. The error seems to be on line 251 in "fmi2.py" when trying to instatiate. Why is this error coming? Does additional information need to be provided? 

```python
Traceback (most recent call last):

  File "_ctypes/callbacks.c", line 237, in 'calling callback function'

File "C:\Users\1990phkj\Anaconda3\lib\site-packages\fmpy\fmi1.py", line 88, in printLogMessage
    print("[%s] %s" % (label, message.decode("utf-8")))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 19: invalid start byte

[ERROR] [EXTME2][DXFMUversion3_1][DXFMUversion3_1][instantiate_DXFMUversion3_1] could not not load shared library
Traceback (most recent call last):

  File "C:\Users\1990phkj\Documents\IoT_Suite\Cognite\TwinBuilderSimulation\DT\VM\RunTwinFMU.py", line 93, in <module>
    res = fmpy.simulate_fmu(fmu, validate=True, start_time=0, stop_time=10, step_size=0.001, input=signal, output_interval=1)

  File "C:\Users\1990phkj\Anaconda3\lib\site-packages\fmpy\simulation.py", line 688, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, use_remoting)

  File "C:\Users\1990phkj\Anaconda3\lib\site-packages\fmpy\simulation.py", line 764, in instantiate_fmu
    fmu.instantiate(visible=visible, callbacks=callbacks, loggingOn=debug_logging)

  File "C:\Users\1990phkj\Anaconda3\lib\site-packages\fmpy\fmi2.py", line 260, in instantiate
    raise Exception("Failed to instantiate model")

Exception: Failed to instantiate model
```

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by PhillipEDRDK** [comment]
Yes, but I don't want to leave it here. Could you provide an e-mail that I can send it to or another private file transfer method.

**Comment by t-sommer** [comment]
You can send it to torsten.sommer@3ds.com.
