### ISSUE TITLE
Remoting FMUs do not work inside container fmus

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#291]
When putting an FMU with remoting in a container fmu, the resulting container does not work.

Steps to reproduce:

1.  Remove current platform binary from BouncingBall fmu
2. `fmpy add-remoting BouncingBall.fmu`
3. Run the following code to create a container fmu
```
from fmpy.fmucontainer import create_fmu_container, Variable, Connection
configuration = {
'description': 'remoting test',
'variables': [Variable('Real', 'continuous', 'output', 'h', '1', 'h', [('BouncingBall','h')]),
Variable('Real', 'continuous', 'output', 'v', '1', 'v', [('BouncingBall','v')])],
'components': [{
  'filename': 'BouncingBall.fmu',
  'name': 'BouncingBall'}],
'connections':[]}
create_fmu_container(configuration,'BB_container.fmu')
```
4. `fmpy simulate BB_container.fmu` gives the following output:
```
Traceback (most recent call last):
  File "/home/user/fmpy/bin/fmpy", line 11, in <module>
    sys.exit(main())
  File "/home/user/fmpy/lib/python3.6/site-packages/fmpy/command_line.py", line 164, in main
    fmi_call_logger=fmi_call_logger)
  File "/home/user/fmpy/lib/python3.6/site-packages/fmpy/simulation.py", line 783, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, library_path)
  File "/home/user/fmpy/lib/python3.6/site-packages/fmpy/simulation.py", line 860, in instantiate_fmu
    fmu.instantiate(visible=visible, callbacks=callbacks, loggingOn=debug_logging)
  File "/home/user/fmpy/lib/python3.6/site-packages/fmpy/fmi2.py", line 260, in instantiate
    raise Exception("Failed to instantiate model")
Exception: Failed to instantiate model
```

**Comment by t-sommer** [comment]
Fixed with 6515b29f797bc73db7cfd8073ef39a19e87adc49.
