### ISSUE TITLE
Cannot find shared library /tmp/xxx/xxx/xxx.so on Linux. fmu with no dependency

### ISSUE THREAD

**Issue by Lokkii999** [CATIA-Systems/FMPy#330]
Hi!
    I meet some problem, while my fmu runs ok with FMpy on Windows, it throws error on Linux as follow or jpg attached:
      'raise Exception("Cannot find shared library %s." % libraryPath)
      Exception: Cannot find shared library /tmp/tmp8nij0irz/binaries/linux64/FMISample_FMUADD_Start.so.'
![no so file on Linux_FMpy](https://user-images.githubusercontent.com/79065939/138576244-2cf7caa1-055c-494f-addc-b5a4fb02ecf4.JPG)

    1. Error info as above on Linux, no other dependency of this fmu file. 
    2. After runned FMpy on Linux,I only found folder Windows64/Windows32 under folder binaries, no linux64 folder & .so file under it.
    3. Windows env: python 3.8.3 64bit, all FMpy requirements installed
        Linux env: python 3.8.3 64bit, all FMpy requirements installed
    4. My core-code as attached, which is for the function of custom_input in my fmu(simply sum,max,min). And it follows FMpy guide and runned ok on Windows.
![core_code](https://user-images.githubusercontent.com/79065939/138576347-bbf32454-378d-412f-bd1b-114c5cc92ff6.JPG)
    5. fum file as attached
[FMISample_FMUADD_Start.zip](https://github.com/CATIA-Systems/FMPy/files/7403922/FMISample_FMUADD_Start.zip)

    I am not sure the reason of  the problem,because it's ok on Windows with same FMpy, same fmu, same code.
    Hope for your help.Thank you in advance!

**Comment by zhangbin006** [comment]
I also encounter this problem, how to solve it

**Comment by SchmJo** [comment]
Why is this issue closed? For me the problem still exists. The suggested solution is not working. In my case the command `fmpy compile FoxesFMU.fmu` throws the following error (my example fmu is a almost empty dummy):
```
Compiling platform binary...
/tmp/tmpoc_hcw3r/sources
gcc -c -fPIC -I. -I/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/c-code  headers/pythonfmu/PySlaveInstance.hpp headers/pythonfmu/PyState.hpp headers/cppfmu/cppfmu_common.hpp headers/cppfmu/cppfmu_cs.hpp cpp/cppfmu_cs.cpp cpp/fmi_functions.cpp cpp/PySlaveInstance.cpp CMakeLists.txt && gcc -static-libgcc -shared -oFoxesFMU.so *.o -lm
headers/pythonfmu/PySlaveInstance.hpp:5:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    5 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
headers/pythonfmu/PyState.hpp:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
headers/cppfmu/cppfmu_common.hpp:24:14: fatal error: fmi/fmi2Functions.h: No such file or directory
   24 | #    include "fmi/fmi2Functions.h"
      |              ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from headers/cppfmu/cppfmu_cs.hpp:9:
headers/cppfmu/cppfmu_common.hpp:24:14: fatal error: fmi/fmi2Functions.h: No such file or directory
   24 | #    include "fmi/fmi2Functions.h"
      |              ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/cppfmu_cs.cpp:6:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    6 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/fmi_functions.cpp:6:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    6 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/PySlaveInstance.cpp:2:10: fatal error: pythonfmu/PySlaveInstance.hpp: No such file or directory
    2 | #include "pythonfmu/PySlaveInstance.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/bin/fmpy", line 8, in <module>
    sys.exit(main())
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/command_line.py", line 99, in main
    compile_platform_binary(filename=args.fmu_filename,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/util.py", line 906, in compile_platform_binary
    binary = compile_dll(model_description=model_description,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/util.py", line 880, in compile_dll
    raise Exception('Failed to compile shared library')
Exception: Failed to compile shared library
```
Am I missing a path setting or something similar?
Can anybody help? Thanks!

**Comment by 2018-Summer** [comment]
You can try compiling the fmu with pythonfmu

**Comment by SchmJo** [comment]
Thanks for the quick response! But still, running
```console
pythonfmu build -f sinusGenerator.py
```
on a super simple python file, and then
```console
fmpy simulate SinusGenerator.fmu
```
I still get the error
```
Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi1.py", line 161, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/bin/fmpy", line 8, in <module>
    sys.exit(main())
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/command_line.py", line 161, in main
    result = simulate_fmu(args.fmu_filename,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/simulation.py", line 738, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/simulation.py", line 819, in instantiate_fmu
    fmu = FMU2Slave(**fmu_args)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi2.py", line 524, in __init__
    super(FMU2Slave, self).__init__(**kwargs)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi2.py", line 85, in __init__
    super(_FMU2, self).__init__(**kwargs)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi1.py", line 163, in __init__
    raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
Exception: Failed to load shared library /tmp/tmpp5jtvvyi/binaries/linux64/SinusGenerator.so. libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by 2018-Summer** [comment]
I also encountered this problem, and it is not solved, recompiled this libpython3.9.so.1.0 file, still did not solve this problem

**Comment by 2018-Summer** [comment]
You can also compile fmu with matlab simulate and you can load successfully in linux

**Comment by SchmJo** [comment]
I do not own matlab, sorry

**Comment by SchmJo** [comment]
I posted a solution that worked in my case on #435
