### ISSUE TITLE
fmpy.webapp fails because of AttributeError due to deprecation

### ISSUE THREAD

**Issue by dietmarw** [CATIA-Systems/FMPy#339]
Trying to run `python -m fmpy.webapp example.fmu` results in a `AttributeError`. Here the output from running it on Ubuntu Linux 20.04 in its own virtenv:

```
$ python -m fmpy.webapp example.fmu
/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/webapp/__main__.py:4: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/webapp/__main__.py:6: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
Extracting FMU to /tmp/tmp6x_w52g4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/webapp/__main__.py", line 63, in <module>
    row = dbc.FormGroup(
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/dash_bootstrap_components/__init__.py", line 52, in __getattr__
    raise AttributeError(
AttributeError: FormGroup was deprecated in dash-bootstrap-components version 1.0.0. You are using 1.0.0. For more details please see the migration guide: https://dbc-v1.herokuapp.com/migration-guide/
```

**Comment by dietmarw** [comment]
Reading a bit into it, it looks like `FormGroup` needs to get replaced by the alternative usage of `Row Col` . See [migration guide](https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/)

**Comment by dietmarw** [comment]
Removing  `FormGroup` then triggers `InputGroupAddon` not being available any more. But here I stopped.

**Comment by dietmarw** [comment]
Simple workaround is to pin DBC for now:
```
pip install dash-bootstrap-components==0.13.1
```
