### ISSUE TITLE
`fmu.instantiate()` Exception: Failed to instantiate model

### ISSUE THREAD

**Issue by Andrea8Testa** [CATIA-Systems/FMPy#391]
Hi all, first of all, thank you for the effort to develop and maintain this package.

I am trying to change the parameters of the simulation using `setReal()`. Before, I need to instantiate the FMU file, but I get an error I am not able to solve.
 
Code:
```
import fmpy
from fmpy.fmi2 import FMU2Slave

fmu_file = "simulation_indirect_MPC.fmu"
print(f"Simulate {fmu_file}")
fmpy.dump(fmu_file)

model_description = fmpy.read_model_description(fmu_file)

unzip_dir = fmpy.extract(fmu_file)

fmu = FMU2Slave(
    guid=model_description.guid,
    unzipDirectory=unzip_dir,
    modelIdentifier=model_description.coSimulation.modelIdentifier,
)

fmu.instantiate()
```
Output:
```
Simulate simulation_indirect_MPC.fmu

Model Info

  FMI Version        2.0
  FMI Type           Co-Simulation
  Model Name         simulation_indirect_MPC
  Description        
  Platforms          darwin64, linux64, win64
  Continuous States  0
  Event Indicators   0
  Variables          9
  Generation Tool    Simulink (R2020b)
  Generation Date    2022-03-31T13:18:09Z

Default Experiment

  Stop Time          2.5
  Step Size          0.001

Variables (input, output)

  Name               Causality              Start Value  Unit     Description
  Output             output                                       Output Port: Output
  Output1            output                                       Output Port: Output1
  Output2            output                                       Output Port: Output2
  Output3            output                                       Output Port: Output3
Traceback (most recent call last):
  File "/home/andreatesta/src/MPCfromFMU/example.py", line 18, in <module>
    fmu.instantiate()
  File "/home/andreatesta/.local/lib/python3.8/site-packages/fmpy/fmi2.py", line 260, in instantiate
    raise Exception("Failed to instantiate model")
Exception: Failed to instantiate model
```
Do you know what is the problem?
Thank you in advance.

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by Andrea8Testa** [comment]
Found the problem, I just didn't started the session to simulate the FMU. Thanks
