### ISSUE TITLE
Failing to load shared library for Windows FMI1.0

### ISSUE THREAD

**Issue by BjorHart** [CATIA-Systems/FMPy#402]
I have an Azure Windows App Service where I am running python=3.6.4 and am able to run the standard example bouncingBall.fmu.
When trying another FMU, where the FMI=1.0, an exception occurs, failing to load shared library, although I can see the library is in the path specified. The fmu has win64 binaries and the App Service runs AMD64 processor architechture. This is the same architechture as I run locally, where the FMU seems to work. 

I realize this is little to go on, but are there any suggestions on how to debug this? I cant seem to figure it out.

Below are "proof of architechture", "proof of file" and the complete error traceback:

proof of file:
```
C:\local\Temp\tmp7nb9o8qr\binaries\win64>dir | grep -e mopsolver
06/01/2022  08:24 AM           354,304 mopsolver_fmu.dll
06/01/2022  08:24 AM        13,155,328 mopsolver_no_ctm.dll
```

proof of architechture:
```
C:\local\Temp\tmp7nb9o8qr\binaries\win64>echo %PROCESSOR_ARCHITECTURE%
AMD64
```

complete traceback:
```
Traceback (most recent call last):
  File "D:\home\site\wwwroot\dependencies\fmpy\fmi1.py", line 161, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\ctypes\__init__.py", line 426, in LoadLibrary
  File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\ctypes\__init__.py", line 348, in __init__
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\runpy.py", line 193, in _run_module_as_main
  File "E:\A\_work\79\b\source_packages\python.3.6.4\tools\Lib\runpy.py", line 85, in _run_code
  File "D:\home\site\wwwroot\dependencies\fmpy\__main__.py", line 4, in <module>
    main()
  File "D:\home\site\wwwroot\dependencies\fmpy\command_line.py", line 177, in main
    fmi_call_logger=fmi_call_logger)
  File "D:\home\site\wwwroot\dependencies\fmpy\simulation.py", line 738, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode)
  File "D:\home\site\wwwroot\dependencies\fmpy\simulation.py", line 830, in instantiate_fmu
    fmu = FMU1Model(**fmu_args)
  File "D:\home\site\wwwroot\dependencies\fmpy\fmi1.py", line 554, in __init__
    super(FMU1Model, self).__init__(**kwargs)
  File "D:\home\site\wwwroot\dependencies\fmpy\fmi1.py", line 264, in __init__
    super(_FMU1, self).__init__(**kwargs)
  File "D:\home\site\wwwroot\dependencies\fmpy\fmi1.py", line 163, in __init__
    raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
Exception: Failed to load shared library C:\local\Temp\tmp7nb9o8qr\binaries\win64\mopsolver_fmu.dll. [WinError 126] The specified module could not be found
```

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by BjorHart** [comment]
sorry, sadly not, it is confidential...
Any debugging suggestions?

**Comment by t-sommer** [comment]
Can you check with [Dependency Walker](https://www.dependencywalker.com/) if all dependent DLLs are available on the target system? If so, please reopen.
