### ISSUE TITLE
list.clear() method is not available under Python 2.x 

### ISSUE THREAD

**Issue by Vaitek** [CATIA-Systems/FMPy#41]
https://github.com/CATIA-Systems/FMPy/blob/259c5a85c88fc6178f1dca9e7e4e9ad870355c66/fmpy/gui/model.py#L197

Can't use fmpy.gui under Python 2.7.12 due to:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/fmpy/gui/__main__.py", line 468, in open
    self.load(filename)
  File "/home/user/.local/lib/python2.7/site-packages/fmpy/gui/__main__.py", line 399, in load
    self.treeModel.setModelDescription(md)
  File "/home/user/.local/lib/python2.7/site-packages/fmpy/gui/model.py", line 197, in setModelDescription
    self.rootItem.children.clear()
AttributeError: 'list' object has no attribute 'clear'
Aborted (core dumped)
```

**Comment by t-sommer** [comment]
@Vaitek, can you give b1be0cccd638d9facafbbd4df34b43099e16829c a spin and let us know if it works for you?

**Comment by Vaitek** [comment]
Yes it works, now GUI can open models.

**Comment by t-sommer** [comment]
Thanks
