### ISSUE TITLE
Set communication step size for CS FMU in GUI

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#52]
It would be nice to be able to set the (commication) step size for CS FMUs in the GUI.
Currently the field "step size" is greyed out, and one can only enter "Max. samples" which seems to be the number of equidistant communication timesteps.

**Comment by t-sommer** [comment]
Can you describe a use case where this would be necessary?

**Comment by t-sommer** [comment]
@chrbertsch, so what you actually want to set is the `output_interval` parameter that's passed to `simulate_fmu()`?

**Comment by chrbertsch** [comment]
Yes. (This will be the macro timestep of the for the CS FMU, right?)

**Comment by t-sommer** [comment]
@chrbertsch, can you give ebbc765 a try?

**Comment by chrbertsch** [comment]
I tried to verify the commit but failed with running the gui. Any hints?
```

(base) C:\home>conda create -n fmpy-feature python=3.7
Solving environment: done

## Package Plan ##

  environment location: C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.33.4               |           py37_0          57 KB  defaults
    certifi-2019.3.9           |           py37_0         155 KB  defaults
    pip-19.1.1                 |           py37_0         1.8 MB  defaults
    ca-certificates-2019.5.15  |                0         166 KB  defaults
    setuptools-41.0.1          |           py37_0         680 KB  defaults
    python-3.7.3               |       h8c8aaf0_1        17.8 MB  defaults
    sqlite-3.28.0              |       he774522_0         945 KB  defaults
    ------------------------------------------------------------
                                           Total:        21.5 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2019.5.15-0       defaults
    certifi:         2019.3.9-py37_0   defaults
    openssl:         1.1.1-he774522_0  defaults
    pip:             19.1.1-py37_0     defaults
    python:          3.7.3-h8c8aaf0_1  defaults
    setuptools:      41.0.1-py37_0     defaults
    sqlite:          3.28.0-he774522_0 defaults
    vc:              14.1-h21ff451_3   defaults
    vs2015_runtime:  15.5.2-3          defaults
    wheel:           0.33.4-py37_0     defaults
    wincertstore:    0.2-py37_0        defaults

Proceed ([y]/n)? y


Downloading and Extracting Packages
wheel 0.33.4: ################################################################################################# | 100%
certifi 2019.3.9: ############################################################################################# | 100%
pip 19.1.1: ################################################################################################### | 100%
ca-certificates 2019.5.15: #################################################################################### | 100%
setuptools 41.0.1: ############################################################################################ | 100%
python 3.7.3: ################################################################################################# | 100%
sqlite 3.28.0: ################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate fmpy-feature
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\home>conda activate fmpy-feature

(fmpy-feature) C:\home>python -m pip install https://github.com/CATIA-Systems/FMPy/archive/develop.zip
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Collecting https://github.com/CATIA-Systems/FMPy/archive/develop.zip
  Downloading https://github.com/CATIA-Systems/FMPy/archive/develop.zip
     \ 3.4MB 1.3MB/s
Collecting lxml (from FMPy==0.2.11)
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/b8/5a/bb7f48b4e06ed60055c8bf2ea7d8259dae40a55dc03104cd7b0782699b9a/lxml-4.3.3-cp37-cp37m-win_amd64.whl (3.6MB)
     |████████████████████████████████| 3.6MB 1.1MB/s
Collecting numpy (from FMPy==0.2.11)
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/ce/61/be72eee50f042db3acf0b1fb86650ad36d6c0d9be9fc29f8505d3b9d6baa/numpy-1.16.4-cp37-cp37m-win_amd64.whl (11.9MB)
     |████████████████████████████████| 11.9MB 1.7MB/s
Collecting pathlib (from FMPy==0.2.11)
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
     |████████████████████████████████| 51kB 544kB/s
Collecting pywin32 (from FMPy==0.2.11)
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/a3/8a/eada1e7990202cd27e58eca2a278c344fef190759bbdc8f8f0eb6abeca9c/pywin32-224-cp37-cp37m-win_amd64.whl (9.0MB)
     |████████████████████████████████| 9.1MB 1.1MB/s
Building wheels for collected packages: FMPy, pathlib
  Building wheel for FMPy (setup.py) ... done
  Stored in directory: C:\Users\cbt2si\AppData\Local\Temp\pip-ephem-wheel-cache-uw3ossik\wheels\bf\ef\7b\0504fd33e3896b4067c578165a29739bbda1d897e8ff7a0970
  Building wheel for pathlib (setup.py) ... done
  Stored in directory: C:\Users\cbt2si\AppData\Local\pip\Cache\wheels\46\d3\82\4361e913316df988d5e74c44278ab764d90c784a9072a026a6
Successfully built FMPy pathlib
Installing collected packages: lxml, numpy, pathlib, pywin32, FMPy
Successfully installed FMPy-0.2.11 lxml-4.3.3 numpy-1.16.4 pathlib-1.0.1 pywin32-224

(fmpy-feature) C:\home>python -m fmpy.gui
Traceback (most recent call last):
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\site-packages\fmpy\gui\__main__.py", line 6, in <module>
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5'

(fmpy-feature) C:\home>pip install pyqt5
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Collecting pyqt5
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/f4/2c/d59dc21d5464f4bef3d58a1a1670a58ed14989f4642f6cf4ef8b7043c423/PyQt5-5.12.2-5.12.3-cp35.cp36.cp37.cp38-none-win_amd64.whl (47.5MB)
     |████████████████████████████████| 47.6MB 119kB/s
Collecting PyQt5_sip<13,>=4.19.14 (from pyqt5)
  Downloading https://rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/packages/76/05/a65bb95c1f5a9f4a7dcbecbd0a8f8c4b9a9231aa40f600cde4a00635b5d4/PyQt5_sip-4.19.17-cp37-none-win_amd64.whl (51kB)
     |████████████████████████████████| 61kB 491kB/s
Installing collected packages: PyQt5-sip, pyqt5
Successfully installed PyQt5-sip-4.19.17 pyqt5-5.12.2

(fmpy-feature) C:\home>python -m fmpy.gui
Traceback (most recent call last):
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\site-packages\fmpy\gui\__main__.py", line 7, in <module>
    from fmpy.gui.MainWindow import MainWindow
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\site-packages\fmpy\gui\MainWindow.py", line 16, in <module>
    from fmpy.gui.generated.MainWindow import Ui_MainWindow
ModuleNotFoundError: No module named 'fmpy.gui.generated.MainWindow'

(fmpy-feature) C:\home>

```

**Comment by t-sommer** [comment]
The Qt UI Compiler (UIC) needs to be installed when you install FMPy from source to generate `fmpy.gui.generated.MainWindow`. See also [hacking.md#setup-your-python-environment](https://github.com/CATIA-Systems/FMPy/blob/master/docs/hacking.md#setup-your-python-environment).

**Comment by chrbertsch** [comment]
https://github.com/CATIA-Systems/FMPy/blob/master/docs/hacking.md#setup-your-python-environment does not seem to  mention the Qt UI compiler or how to install/use it.

**Comment by t-sommer** [comment]
UIC is part of PyQt5. The problem is that (according to the error above) that you have built the Python wheel _before_ installing PyQt5.

**Comment by chrbertsch** [comment]
I have installed all the packages and built the wheel again. Still errors ...
```

(base) C:\home>activate fmpy-feature

(fmpy-feature) C:\home>conda install dask lxml matplotlib numpy pathlib pyqt pyqtgraph pywin32 
(...)
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(fmpy-feature) C:\home>python -m pip install https://github.com/CATIA-Systems/FMPy/archive/develop.zip
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Collecting https://github.com/CATIA-Systems/FMPy/archive/develop.zip
  Downloading https://github.com/CATIA-Systems/FMPy/archive/develop.zip
     - 3.3MB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): FMPy==0.2.11 from https://github.com/CATIA-Systems/FMPy/archive/develop.zip in c:\users\cbt2si\appdata\local\conda\conda\envs\fmpy-feature\lib\site-packages
Requirement already satisfied: lxml in c:\users\cbt2si\appdata\local\conda\conda\envs\fmpy-feature\lib\site-packages (from FMPy==0.2.11) (4.3.3)
Requirement already satisfied: numpy in c:\users\cbt2si\appdata\local\conda\conda\envs\fmpy-feature\lib\site-packages (from FMPy==0.2.11) (1.16.4)
Requirement already satisfied: pathlib in c:\users\cbt2si\appdata\local\conda\conda\envs\fmpy-feature\lib\site-packages (from FMPy==0.2.11) (1.0.1)
Requirement already satisfied: pywin32 in c:\users\cbt2si\appdata\local\conda\conda\envs\fmpy-feature\lib\site-packages (from FMPy==0.2.11) (224)
Building wheels for collected packages: FMPy
  Building wheel for FMPy (setup.py) ... done
  Stored in directory: C:\Users\cbt2si\AppData\Local\Temp\pip-ephem-wheel-cache-0m3wzz49\wheels\bf\ef\7b\0504fd33e3896b4067c578165a29739bbda1d897e8ff7a0970
Successfully built FMPy

(fmpy-feature) C:\home>python -m fmpy.gui
Traceback (most recent call last):
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\site-packages\fmpy\gui\__main__.py", line 7, in <module>
    from fmpy.gui.MainWindow import MainWindow
  File "C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpy-feature\lib\site-packages\fmpy\gui\MainWindow.py", line 16, in <module>
    from fmpy.gui.generated.MainWindow import Ui_MainWindow
ModuleNotFoundError: No module named 'fmpy.gui.generated.MainWindow'

```

**Comment by t-sommer** [comment]
This works for me:

```
conda create -q -n fmpy-dev -c conda-forge python=3.7 dask lxml matplotlib numpy pathlib pyqt pyqtgraph pywin32 requests
activate fmpy-dev
python -m pip install https://github.com/CATIA-Systems/FMPy/archive/develop.zip
python -m fmpy.gui
```

**Comment by chrbertsch** [comment]
This installation order worked fine. 
I verified the new feature for setting the communication timestep.  Thanks.
