### ISSUE TITLE
Update error?

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#536]
Anaconda3 on Windows10

After updating fmpy, fmpy.gui tells me v0.3.15 but github shows v0.3.14 as latest version. What's wrong?

When opening an fmu, I can't simulate and I get an error message in the Anaconda window:
Traceback (most recent call last):
  File "C:\Users\AHaumer\AppData\Roaming\Python\Python39\site-packages\fmpy\gui\MainWindow.py", line 601, in open
    self.load(filename)
  File "C:\Users\AHaumer\AppData\Roaming\Python\Python39\site-packages\fmpy\gui\MainWindow.py", line 537, in load
    self.ui.filesTreeView.expandRecursively(root_index, 10)
AttributeError: 'QTreeView' object has no attribute 'expandRecursively'
Again, what's wrong? 

I urgently need a solution for student's projects ...

**Comment by AHaumer** [comment]
Ok after updating Anaconda it works as before.
What remains (but I don't mind): fmpy.gui reports a higher version than the latest officical release.
