### ISSUE TITLE
Exception: Function fmi2GetDirectionalDerivative is missing in shared library.

### ISSUE THREAD

**Issue by LordEvron** [CATIA-Systems/FMPy#545]
I recently upgraded the fmpy from v **0.3.12** --> **0.3.13** and this error pops up after the fmpy package update. 

```
import fmpy
fmpy.simulate_fmu("MYFMU.fmu")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File " python3.10/site-packages/fmpy/simulation.py", line 738, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode, None, validate)
  File "python3.10/site-packages/fmpy/simulation.py", line 836, in instantiate_fmu
    fmu = FMU2Model(**fmu_args)
  File "/python3.10/site-packages/fmpy/fmi2.py", line 419, in __init__
    super(FMU2Model, self).__init__(**kwargs)
  File "python3.10/site-packages/fmpy/fmi2.py", line 173, in __init__
    self._fmi2Function('fmi2GetDirectionalDerivative',
  File "python3.10/site-packages/fmpy/fmi2.py", line 190, in _fmi2Function
    raise Exception(f"Function {fname} is missing in shared library.")
Exception: Function fmi2GetDirectionalDerivative is missing in shared library.
```

 
**This bug affect version 0.3.13, 0.3.14, 0.3.15** but all the versions previous 0.3.13 can simulate the same fmu file just fine (so i will continue using v 0.3.12). 

This is the code that is being executed: 

```
import fmpy
fmpy.simulate_fmu("MYFMU.fmu")
```

Unfortunately i cannot share the FMU model used.

**Comment by t-sommer** [comment]
`fmi2GetDirectionalDerivative()` is a required function for FMI 2.0 Co-Simulation FMUs, so your FMU does not seem to be a valid FMU.

From the FMI 2.0.4 Specification, p. 70:

> An FMU has to implement all common functions (according to tables in sections 3.2.3 and 4.2.4).
ModelExchange FMUs have to provide additionally the respective Model Exchange function,
CoSimulation FMUs the Co-Simulation functions.

You can double check the exported functions with [Dependencies](https://github.com/lucasg/Dependencies) on Windows or `nm -gD MYFMU.so` on Linux.
