### ISSUE TITLE
array support for Binary datatype

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [CATIA-Systems/FMPy#604]
I am trying to send array of binary data.
**e.g. call of function**    setBinary([1], [b'CHECK', b'OUTPUT', b'CLEAR'])

@ fmi3.py: line no 781    , getting invalid index error
 size = (c_size_t * len(vr))(*[len(v) for v in values])

do binary type support array ? 

**Traceback (most recent call last):**
  File 
    simulate_custom_input()
  File "C:\Project\New_Project_Setup\_bin\lib\Windows\Debug\x86\TestFMI3.py", line 104, in simulate_custom_input
    fmu.setBinary([binary_input_VR],[binary_input_value, binary_input_value, binary_input_value, binary_input_value])
  File "C:\User\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\fmpy\fmi3.py", line 791, in setBinary
    size = (c_size_t * len(vr))(*[len(v) for v in values])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: invalid index

**Comment by t-sommer** [comment]
Arrays of type `Binary` are currently not supported.

**Comment by chrbertsch** [comment]
> This is as per fmi standard ? I saw in documentation that only for clock types array not supported.

The FMI standard allows binary arrays. 
Tools such as fmpy are currently implementing the FMI 3.0 features step by step

**Comment by molokov** [comment]
I've just noticed this myself too.

What should be at https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/fmi3.py#L705 is:

```
size = (c_size_t * nValues)()
```
and at https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/fmi3.py#L781 is:

```
size = (c_size_t * len(values))(*[len(v) for v in values])
```

This would support Binary arrays, and match the standard quote (emphasis mine):

> nValues provides the number of values in the values vector (*and valueSizes vector*, where applicable) which is *only equal to nValueReferences if all [valueReference](https://fmi-standard.org/docs/3.0.2/#valueReference)s point to scalar variables*.

(i.e. `valueSizes` should be the same size as `values` not the same size as `valueReferences` if any variable is an array).

I will fix this in a fork and request a PR.

**Comment by molokov** [comment]
A full fix for this and #743 is now attached to my comment in #748

**Comment by molokov** [comment]
Fixed by PR #754
