### ISSUE TITLE
pip install fmpy fails with 0.3.17

### ISSUE THREAD

**Issue by behrisch** [CATIA-Systems/FMPy#607]
If I try `pip install fmpy` in a fresh virtualenv on ubuntu 22.04 I get
```
Collecting fmpy
  Using cached FMPy-0.3.17-py2.py3-none-any.whl (8.4 MB)
Collecting lark
  Using cached lark-1.1.7-py3-none-any.whl (108 kB)
Collecting numpy
  Using cached numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting msgpack
  Using cached msgpack-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (530 kB)
Collecting Jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting lxml
  Using cached lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
Collecting pytz
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Collecting attrs
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: pytz, numpy, msgpack, MarkupSafe, lxml, lark, attrs, Jinja2, fmpy
ERROR: Exception:
Traceback (most recent call last):
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 405, in run
    installed = install_given_reqs(
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 769, in install
    install_wheel(
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
    _install_wheel(
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 690, in _install_wheel
    rows = get_csv_rows_for_installed(
  File "/home/micha/programming/sumo/tools/p/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 258, in get_csv_rows_for_installed
    old_record_path = cast("RecordPath", row[0])
IndexError: list index out of range
```

Updating pip does not help but everything is fine with  fmpy==0.3.16

**Comment by MartinBischoff** [comment]
I can confirm this error in version 0.3.17. Everything is fine with v0.3.16 though.
```
 InvalidRecordEntry

  Row Index 0: expected 3 elements, got 0

  at <...>\records.py:214 in parse_record_file
      210│         if len(elements) != 3:
      211│             message = "Row Index {}: expected 3 elements, got {}".format(
      212│                 row_index, len(elements)
      213│             )
    → 214│             raise InvalidRecordEntry(elements=elements, issues=[message])
      215│
      216│         # Convert Windows paths to use / for consistency
      217│         elements[0] = elements[0].replace("\\", "/")
      218│

Warning: Validation of the RECORD file of FMPy-0.3.17-py2.py3-none-any.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
Unable to retrieve `RECORD` from <...>\FMPy-0.3.17-py2.py3-none-any.whl: InvalidRecordEntry(elements=[], issues=['Row Index 0: expected 3 elements, got 0'])
```

**Comment by ClemensLinnhoff** [comment]
Ich have the same problem.

**Comment by t-sommer** [comment]
Can you try to run the command twice?

**Comment by behrisch** [comment]
> > Can you try to run the command twice?
> 
> When I run the command twice, I don't get the error the second time.

same here

**Comment by 12Tall** [comment]
Seems on Windows system has the similar issue, and installing twice worked.

**Comment by t-sommer** [comment]
Can you give 1320ae981db84987e6e20ac616042b996699b576 a try?

**Comment by NiekTeeuwenVO** [comment]
> Can you give [1320ae9](https://github.com/CATIA-Systems/FMPy/commit/1320ae981db84987e6e20ac616042b996699b576) a try?
> 
> [merged.zip (build #20231013.2)](https://github.com/CATIA-Systems/FMPy/files/12892774/merged.zip)

This installs flawlessly on my machine (Windows, python 3.11.4)
