### ISSUE TITLE
fmpy.sundials not importable on MacOS Apple Silicon in version 0.3.20

### ISSUE THREAD

**Issue by miki5799** [CATIA-Systems/FMPy#661]
After installing fmpy(0.3.20) via pip (3.9.19 , 3.10.14, 3.12.2 respectively) on my MacOS machine (Apple Silicon M1) the following error occurs when attempting to import the fmpy.sundials module: 
```
>>> import fmpy.sundials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/__init__.py", line 4, in <module>
    from .cvode import *
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/cvode.py", line 1, in <module>
    from .libraries import sundials_cvode
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/libraries.py", line 8, in <module>
    sundials_nvecserial     = cdll.LoadLibrary(os.path.join(library_dir, platform_tuple, 'sundials_nvecserial'     + sharedLibraryExtension))
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib, 0x0006): tried: '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file)>>> import fmpy.sundials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/__init__.py", line 4, in <module>
    from .cvode import *
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/cvode.py", line 1, in <module>
    from .libraries import sundials_cvode
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/libraries.py", line 8, in <module>
    sundials_nvecserial     = cdll.LoadLibrary(os.path.join(library_dir, platform_tuple, 'sundials_nvecserial'     + sharedLibraryExtension))
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib, 0x0006): tried: '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file)
```

installing sundials with brew did not resolve this 

Note that this happens only in version 0.3.20

**Comment by t-sommer** [comment]
Can you import `fmpy.sundials` with FMPy 0.3.19 on Apple Silicon?

**Comment by miki5799** [comment]
It seems like this issue is reappearing since I am again not able to import the sundials package from fmpy==0.3.20

**Comment by t-sommer** [comment]
Can you share the error message?

**Comment by miki5799** [comment]
```
>>> import fmpy.sundials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/__init__.py", line 4, in <module>
    from .cvode import *
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/cvode.py", line 1, in <module>
    from .libraries import sundials_cvode
  File "<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/libraries.py", line 8, in <module>
    sundials_nvecserial     = cdll.LoadLibrary(os.path.join(library_dir, platform_tuple, 'sundials_nvecserial'     + sharedLibraryExtension))
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(<PathToRepo>/.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib, 0x0006): tried: '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file)>>> import fmpy.sundials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/__init__.py", line 4, in <module>
    from .cvode import *
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/cvode.py", line 1, in <module>
    from .libraries import sundials_cvode
  File "/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/libraries.py", line 8, in <module>
    sundials_nvecserial     = cdll.LoadLibrary(os.path.join(library_dir, platform_tuple, 'sundials_nvecserial'     + sharedLibraryExtension))
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib, 0x0006): tried: '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/<PathToRepo>//.test/lib/python3.9/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file)
```

**Comment by t-sommer** [comment]
This looks exactly like the original error message. Did you install the pre-built wheel from PyPI?

**Comment by miki5799** [comment]
> This looks exactly like the original error message. Did you install the pre-built wheel from PyPI?

Yes, I've tried it again in another environment:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/__init__.py", line 4, in <module>
    from .cvode import *
  File "<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/cvode.py", line 1, in <module>
    from .libraries import sundials_cvode
  File "<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/libraries.py", line 8, in <module>
    sundials_nvecserial     = cdll.LoadLibrary(os.path.join(library_dir, platform_tuple, 'sundials_nvecserial'     + sharedLibraryExtension))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib, 0x0006): tried: '<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file), '<PathToEnv>/lib/python3.11/site-packages/fmpy/sundials/aarch64-darwin/sundials_nvecserial.dylib' (no such file)
```

**Comment by t-sommer** [comment]
Can you check if the file is actually missing? Can you reproduce the problem with other versions of FMPy and Python?

**Comment by miki5799** [comment]
Thanks for the fast reply. Yes the file is actually missing. 

As stated originally this is exclusive to fmpy 0.3.20 on at least (3.9.19 , 3.10.14, 3.12.2 respectively) on my MacOS machine (Apple Silicon M1) and sometimes it stops complaining.

**Comment by t-sommer** [comment]
As a quick fix, can you try to rename the folder `<PathToEnv>/lib/python3.12/site-packages/fmpy/sundials/x86_64-darwin/` to `<PathToEnv>/lib/python3.12/site-packages/fmpy/sundials/aarch64-darwin/`?

**Comment by miki5799** [comment]
Yes that worked for me.
Thanks for suggesting the quick fix, I'd still keep the issue open though

**Comment by sergiochavezlazo96** [comment]
Hello! I am having exactly the same issue now (as well, only for 0.3.2). Any updates on this bug? 
Thank you!!
